FROM node:alpine
WORKDIR /frontend
ENV PATH frontend/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@latest
COPY ./public ./public
COPY ./src ./src
EXPOSE 3000
CMD [ "npm", "start"]